# Generated by Django 3.0.2 on 2020-01-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_boardmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
            ],
        ),
        migrations.CreateModel(
            name='CardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('board_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.BoardMember')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='board_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.List'),
        ),
    ]
