# Generated by Django 3.0.2 on 2020-01-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_cardlabel_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
