# Generated by Django 3.0.2 on 2020-01-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_label_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
