# Generated by Django 3.0.2 on 2020-01-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20200130_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
